Repository ToFuProject/tofu, pull requests merged in 2019-11, with the labels that each got.

#229 Issue228 default separator to dict
  tofu/data/_core.py
  tofu/geom/_core.py
  tofu/utils.py
  tofu/version.py
Labels: portability

#234 Dropping support of Python 2.7
  .travis.yml
  README.md
  conda_recipe/meta.yaml
  setup.py
  tofu/data/_core.py
  tofu/data/_core_new.py
  tofu/geom/_GG.py
  tofu/geom/_GG.pyx
  tofu/geom/_GG03.pyx
  tofu/geom/_core.py
  tofu/geom/utils.py
Labels: portability

#236 [pep8] tofu/geom/_core.py in pep8 conventions
  tofu/geom/_core.py
  tofu/version.py
Labels: bug, enhancement, geom - bug

#242 Bug was not there, but __repr__() now more robust in debug
  tofu/imas2tofu/_core.py
  tofu/utils.py
  tofu/version.py
Labels: bug, geom - bug

#249 Bug fixes in calc_signal and get_sample
  examples/tutorials/tuto_plot_basic.py
  examples/tutorials/tuto_plot_create_geometry.py
  examples/tutorials/tuto_plot_custom_emissivity.py
  tofu/geom/_GG.pyx
  tofu/geom/_basic_geom_tools.pxd
  tofu/geom/_basic_geom_tools.pyx
  tofu/geom/_core.py
  tofu/geom/_fast_sum.c
  tofu/geom/_sampling_tools.pxd
  tofu/geom/_sampling_tools.pyx
  tofu/tests/tests01_geom/tests03_core.py
  tofu/tests/tests09_tutorials/__init__.py
  tofu/tests/tests09_tutorials/tests01_runall.py
  tofu/tests/tests09_tutorials/tuto_plot_basic.py
  tofu/tests/tests09_tutorials/tuto_plot_create_geometry.py
  tofu/tests/tests09_tutorials/tuto_plot_custom_emissivity.py
  tofu/version.py
Labels: geom - bug, top priority

#253 [quick-bf] I variable name was left un-refactored
  tofu/geom/_core.py
Labels: bug

#257 [bug fix #255] found bug
  examples/tutorials/tuto_plot_custom_emissivity.py
  tofu/geom/_GG.pyx
  tofu/geom/_core.py
  tofu/tests/tests09_tutorials/tests01_runall.py
Labels: geom - bug

#254 Feature #252: clearer error and check for emissivity function
  examples/tutorials/tuto_plot_custom_emissivity.py
  tofu/geom/_GG.pyx
  tofu/geom/_core.py
  tofu/tests/tests09_tutorials/tests01_runall.py
  tofu/utils.py
  tofu/version.py
Labels: geom - improve

#251 [Issue #250] added requirements.txt
  requirements.txt
Labels: portability

#226 Br/add more field lines
  tofu/geom/_core.py
  tofu/geom/_plot.py
  tofu/mag/equimap.py
  tofu/mag/magFieldLines.py
  tofu/mag/mag_ripple/__init__.py
  tofu/mag/test_equimap.py
  tofu/mag/test_magFieldLines.py
  tofu/mag/test_ripple.py
  tofu/utils.py
  tofu/version.py
  tofuplot.py
Labels: mag - improve

#258 [py3] took out all tests of python version
  _updateversion.py
  tofu/__init__.py
  tofu/geom/_comp.py
  tofu/tests/tests01_geom/tests01_GG.py
  tofu/utils.py
Labels: portability

#265 Issue264 config names
  tofu/geom/utils.py
  tofu/version.py
Labels: geom - improve

#261 Update in documentation
  README.md
  doc/source/conf.py
  doc/source/contributing.rst
  doc/source/images/pep8speaks.png
  doc/source/images/travis.png
  doc/source/index.rst
  doc/source/installation.rst
  doc/source/modules.rst
  doc/source/tofu.data.rst
  doc/source/tofu.dumpro.rst
  doc/source/tofu.dust.rst
  doc/source/tofu.geom.rst
  doc/source/tofu.rst
  examples/tutorials/tuto_plot_basic.py
  examples/tutorials/tuto_plot_create_geometry.py
  examples/tutorials/tuto_plot_custom_emissivity.py
  tofu/__init__.py
Labels: documentation

#244 Issue243 less verbose warning for missing sub package
  tofu/__init__.py
  tofu/imas2tofu/__init__.py
  tofu/mag/__init__.py
Labels: enhancement

#269 Less verbose warnings for missing sub-packages
  tofu/__init__.py
  tofu/imas2tofu/__init__.py
  tofu/mag/__init__.py
Labels: enhancement

#270 [enhancement] took out the word error from warning
  tofu/__init__.py
Labels: enhancement

#278 [Issue277] Fixed badges and added gitter badge
  README.md
  tofu/version.py
Labels: documentation

#274 #Issue272 Cythonvscython
  conda_recipe/meta.yaml
  doc/source/installation.rst
  doc/source/release_notes/release_notes_141.rst
  requirements.txt
  setup.py
  tofu/geom/_GG.pyx
  tofu/geom/_distance_tools.pyx
  tofu/version.py
Labels: portability

#279 [Issue215] fixed
  tofu/data/_comp.py
  tofu/version.py
Labels: data - bug

#282 Issue281 new default configs
  tofu/geom/inputs/AUG-V0_backup.npz
  tofu/geom/inputs/COMPASS-V0_backup.npz
  tofu/geom/inputs/COMPASS-V1_backup.npz
  tofu/geom/inputs/COMPASS-V2_backup.npz
  tofu/geom/inputs/KSTAR-V0_backup.npz
  tofu/geom/inputs/MAST-V0_backup.npz
  tofu/geom/inputs/TCV-V0_backup.npz
  tofu/geom/inputs/TCV-V1_backup.npz
  tofu/geom/inputs/TFG_Ves_ExpJET_V0.txt
  tofu/geom/inputs/TS-V0_backup.npz
  tofu/geom/inputs/TS-V1_backup.npz
  tofu/geom/inputs/TS-V2_backup.npz
  tofu/geom/utils.py
  tofu/version.py
Labels: geom - improve

#280 Issue218 plasma2d extraction iter
  tofu/data/_comp.py
  tofu/data/_core.py
  tofu/geom/_core.py
  tofu/imas2tofu/_core.py
  tofu/version.py
Labels: data - improve, imas interfacing - bug

#283 Updates in setup.py for pypi installation
  .travis.yml
  pyproject.toml
  setup.py
Labels: portability

#284 [doc] updated format for text modificators in release_notes
  doc/source/release_notes/release_notes_142.rst
  release_notes/release_notes_142.rst
Labels: documentation

#289 [Issue287] IMAS version check operational in imas2tofu.__init__, made…
  tofu/imas2tofu/__init__.py
  tofu/version.py
Labels: imas interfacing - improve

#293 [quick fix] took out wheel deployment and add skip if already in pypi
  .travis.yml
Labels: portability

#299 [Issue292] Hotfix: both solutions
  _updateversion.py
  setup.py
  tofu/version.py
Labels: portability, top priority

#300 New doc
  doc/source/index.rst
  examples/tutorials/tuto_plot_gallery_fusion_machines.py
Labels: documentation

#302 Preparing tofu 1.4.2-a5
  _updateversion.py
  doc/source/index.rst
  examples/tutorials/tuto_plot_gallery_fusion_machines.py
  setup.py
  tofu/tests/tests09_tutorials/tests01_runall.py
  tofu/version.py
Labels: documentation, portability

#305 [Issue304] get_summary() added to Struct and CamLOS2D
  tofu/geom/_core.py
  tofu/version.py
Labels: geom - bug
