Repository ToFuProject/tofu, pull requests merged in 2020-03, with the labels that each got.

#358 Issue #357 Made allow_pickle available to user
  tofu/utils.py
  tofu/version.py
Labels: enhancement

#360 Issue #359 tofu-custom allow customization of script parameters
  tofu/scripts/_def.py
  tofu/scripts/tofucalc.py
  tofu/scripts/tofucustom.py
  tofu/scripts/tofuplot.py
  tofu/version.py
Labels: enhancement

#361 Issue #359 Minor bug fix
  .travis.yml
  release_notes/release_notes_143.rst
  tofu/imas2tofu/_core.py
  tofu/scripts/tofucalc.py
  tofu/scripts/tofuplot.py
  tofu/version.py
Labels: enhancement

#362 Issue #356 openadas interface
  tofu/__init__.py
  tofu/openadas2tofu/__init__.py
  tofu/openadas2tofu/_read_files.py
  tofu/openadas2tofu/_requests.py
  tofu/scripts/tofucustom.py
  tofu/version.py
Labels: New usage

#363 new doc: addition of tuto for scripts
  Notes_Upgrades/Communications/SeminaireStras20/2019_LM_SeminaireStras.tex
  doc/source/index.rst
  doc/source/tofu.data.rst
  doc/source/tofu.geom.rst
  doc/source/tofu.rst
  doc/source/tofu.scripts.rst
  doc/source/tofu.tests.rst
  doc/source/tofu.tests.tests00_root.rst
  doc/source/tofu.tests.tests01_geom.rst
  doc/source/tofu.tests.tests01_geom.tests03_core_data.rst
  doc/source/tofu.tests.tests02_data.rst
  doc/source/tofu.tests.tests09_tutorials.rst
  doc/source/tofu_from_bash.rst
Labels: documentation

#370 Deploy test
  MANIFEST.in
  MANIFEST.txt
  setup.py
  tofu/version.py
Labels: portability

#371 Travis bdist deployment on master
  .travis.yml
Labels: portability
