Repository ToFuProject/tofu, pull requests merged in 2020-02, with the labels that each got.

#342 Updating `devel` with `master` changes
  .travis.yml
  anaconda_upload.sh
  tofu/imas2tofu/_core.py
  tofu/utils.py
  tofu/version.py
  tofucalc.py
  tofuplot.py
Labels: enhancement

#343 Issue341 indchauto
  tofu/geom/_core.py
  tofu/geom/_def.py
  tofu/geom/_plot.py
  tofu/imas2tofu/_core.py
  tofu/utils.py
  tofucalc.py
  tofuplot.py
Labels: imas interfacing - improve

#348 Deploy test
  .travis.yml
  anaconda_upload.sh
  pyproject.toml
  setup.py
  tofu/version.py
Labels: enhancement, portability

#350 Issue349 new imas reflectometer profile
  tofu/imas2tofu/_core.py
  tofu/scripts/tofucalc.py
  tofu/scripts/tofuplot.py
  tofu/version.py
Labels: imas interfacing - update

#352 Issue346 tofucalc mat
  tofu/_physics.py
  tofu/data/_core.py
  tofu/data/_core_new.py
  tofu/imas2tofu/__init__.py
  tofu/imas2tofu/_core.py
  tofu/imas2tofu/_def.py
  tofu/imas2tofu/_mat2ids2calc.py
  tofu/scripts/tofucalc.py
  tofu/utils.py
  tofu/version.py
Labels: enhancement
