Repository ToFuProject/tofu, pull requests merged in 2021-03, with the labels that each got.

#474 Issue #473 explicit arguments for create cam
  examples/tutorials/tuto_plot_basic.py
  examples/tutorials/tuto_plot_custom_emissivity.py
  examples/tutorials/tuto_plot_gallery_fusion_machines.py
  tofu/geom/utils.py
  tofu/version.py
Labels: geom - improve

#476 Issue #475 Remove some easy warnings
  tofu/data/_core.py
  tofu/geom/_core.py
  tofu/geom/_def.py
  tofu/pathfile.py
  tofu/tests/tests01_geom/test_01_GG.py
  tofu/tests/tests02_data/test_03_core.py
  tofu/utils.py
  tofu/version.py
Labels: enhancement

#484 Update doc: known bugs
  doc/source/_updateversion.rst
  doc/source/conf.py
  doc/source/contributing.rst
  doc/source/dev_tutos.rst
  doc/source/installation.rst
  doc/source/modules.rst
  doc/source/release_notes/release_notes_1410.rst
  doc/source/releases.rst
  doc/source/scripts.rst
  doc/source/setup.rst
  doc/source/tofu.data.rst
  doc/source/tofu.dumpro.rst
  doc/source/tofu.dust.rst
  doc/source/tofu.entrypoints.rst
  doc/source/tofu.geom.inputs.rst
  doc/source/tofu.geom.rst
  doc/source/tofu.imas2tofu.rst
  doc/source/tofu.mag.mag_ripple.rst
  doc/source/tofu.mag.rst
  doc/source/tofu.openadas2tofu.rst
  doc/source/tofu.rst
  doc/source/tofu.tests.rst
  doc/source/tofu.tests.tests00_root.rst
  doc/source/tofu.tests.tests01_geom.rst
  doc/source/tofu.tests.tests01_geom.test_03_core_data.rst
  doc/source/tofu.tests.tests01_geom.tests03_core_data.rst
  doc/source/tofu.tests.tests02_data.rst
  doc/source/tofu.tests.tests09_tutorials.rst
  doc/source/tofu_from_bash.rst
  tofu/version.py
Labels: documentation

#493 [#490] Fixed bug introduced by PR #456
  tofu/utils.py
  tofu/version.py
Labels: data - bug
